export const state = ()=> ({
    all: [
                {
                    id: 'lorem',
                    title: 'What is Lorem?',
                    content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id nisi corporis magnam dignissimos officiis dolorum sapiente blanditiis quia? Commodi natus optio impedit autem et libero hic suscipit fuga, deserunt, iusto consequatur ducimus! Facere nesciunt amet et ratione nulla cumque similique iusto, necessitatibus quis incidunt ducimus eos fugiat ad placeat molestias illo sunt quasi eum. Rem, quos. Iusto, libero eaque vero, consequuntur nostrum soluta, doloremque ea temporibus est dignissimos corporis voluptate et at vitae voluptas dolores architecto neque omnis eum obcaecati illum exercitationem. Ullam velit nam animi. Corrupti nostrum et, officiis ab eligendi sit accusantium? Necessitatibus asperiores praesentium autem natus ipsum?'
                },
                {
                    id: 'ipsum',
                    title: 'What is Ipsum?',
                    content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias voluptate accusamus nam vel laborum quae, dignissimos expedita. Dolores saepe, deleniti voluptate suscipit voluptates mollitia maiores hic nobis quasi cumque delectus autem ipsa facere eveniet nam quae, reiciendis doloribus, fugiat laborum rerum incidunt. Magnam enim aspernatur vel asperiores optio nostrum sit dicta ex magni harum reprehenderit officia exercitationem beatae excepturi inventore sequi, dolorum, incidunt perspiciatis unde, aliquid rem laudantium eius fugit. Itaque harum quia laboriosam minima consequatur perferendis rerum consectetur voluptatum tenetur ipsam placeat, magnam doloribus blanditiis at accusantium odit modi ipsa reiciendis debitis numquam a, quae explicabo. Ipsum aspernatur earum quis quasi esse laborum quaerat quod praesentium eum officia laudantium repellendus corrupti repudiandae fuga consequuntur perferendis, dolore, ea deleniti? Mollitia quam quibusdam dolor placeat illo quos, quae a veritatis consequatur deleniti sit, debitis ex quaerat porro! Cum doloremque earum expedita sunt amet nobis odit et, error impedit adipisci. Incidunt maiores sint consequuntur suscipit excepturi a sequi quisquam iste ullam optio ipsum ut possimus officia eveniet similique iusto dicta inventore rerum distinctio, nisi cum placeat. Architecto eveniet magnam tempora maxime voluptatem earum doloremque consectetur officiis, libero qui quibusdam vel eligendi quidem dolores iste dolorum cum recusandae voluptate, modi a aperiam! Repellendus.'
                },
                {
                    id: 'loremIpsum',
                    title: 'What is Lorem-Ipsum?',
                    content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit excepturi quia minus earum asperiores praesentium eveniet beatae, amet eum iste repellendus cumque illo mollitia libero id necessitatibus. Adipisci animi numquam debitis aspernatur saepe maxime quo vero sequi distinctio totam quas sint quisquam, corrupti esse ad et ab asperiores, nihil deleniti accusamus eveniet. Ad earum illum quia perspiciatis ullam tempore quaerat nihil perferendis officia vero. Nihil commodi voluptates eum iusto sint, dolor voluptatum quam quaerat. Blanditiis accusantium laudantium cumque, rem ad molestiae explicabo maxime saepe consequuntur dolorum illum ab ducimus atque distinctio. Quidem ipsum magnam tenetur voluptatum maiores repudiandae? Dolorum dolor, est nam hic corrupti nihil voluptates fuga cum! Voluptate ex, eveniet modi dolorum est veritatis, eaque dolores esse libero doloribus eum eligendi incidunt nam omnis! Fugiat nulla ipsum eum corrupti illo culpa cum enim, molestias similique quo iusto itaque quis? Ullam, soluta! At ipsa, atque repellat velit nesciunt et fugit cum eius iste dicta porro labore a obcaecati reprehenderit? Laborum dolorum quam repellendus. Hic quidem ab laudantium consequatur labore, est ipsam. Totam accusamus esse tempore saepe aperiam. Delectus excepturi nihil quibusdam perspiciatis repellendus, quaerat, architecto doloribus alias reiciendis vel dolore ipsa ad? Mollitia dolore explicabo voluptates dolores nobis aliquam vel veniam distinctio modi quibusdam, fugit eius sapiente voluptatum quis ea odio sed, molestiae ex. Porro eaque et in dignissimos, dicta consequuntur facere fugiat ratione recusandae sint rerum consectetur quidem enim? Maxime incidunt vitae, expedita labore fugit quisquam repellendus nam ab sit, veniam at praesentium sint quaerat nostrum officiis et id! Voluptates praesentium delectus inventore facilis ipsam magnam tempore fuga. Voluptatibus sed, amet nam hic iste quo. Ipsa et dolores non, inventore facere earum ea totam consectetur sapiente tempora error, at dolore cum exercitationem eligendi expedita? Sunt quisquam voluptate, repellat in quia dolores consequatur incidunt eum illum expedita deleniti! Laboriosam, perferendis.'
                },

            ] 
})